name = "GeneralizedEigenvalues"
uuid = "5ca43dd8-00a9-46a1-afdd-d50f1bbb2a5d"
authors = ["Daan Huybrechs <daan.huybrechs@kuleuven.be> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
